name: Deploy to Cloudflare Workers

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    environment: Tiny
    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: "4"
          secrets: |
            STUDIO_PASSWORD
            STRIPE_KEY
            TTBI_SERVICE_KEY
            TS_SERVICE_KEY
        env:
          STUDIO_PASSWORD: ${{ secrets.STUDIO_PASSWORD }}
          STRIPE_KEY: ${{ secrets.STRIPE_KEY }}
          TTBI_SERVICE_KEY: ${{ secrets.TTBI_SERVICE_KEY }}
          TS_SERVICE_KEY: ${{ secrets.TS_SERVICE_KEY }}
